Misc. script updates
: bin/caff, bin/sign-on, script/update, dotfiles.sh

diff --git a/bin/sign-on b/bin/sign-on
--- a/bin/sign-on
+++ b/bin/sign-on
@@ -4,12 +4,20 @@
 # Use this script to do some housekeeping when you sign on.
 #
 # Usage:
-#   [_DEBUG=1] sign-on
-#
+#   [DEBUG=1] sign-on
 
 # shellcheck disable=SC1117
+# shellcheck disable=SC2039
 
-_self="$0"
+
+# Load ~/.dotfiles.conf and $DOTFILES_ROOT/dotfiles.sh.
+# shellcheck disable=SC1090
+. ~/.dotfiles.conf || exit
+. "$DOTFILES_ROOT/dotfiles.sh" || exit
+debug "$0: Loaded ~/.dotfiles.conf and ran $DOTFILES_ROOT/dotfiles.sh OK."
+
+
+_self="${0##*/}"
 
 main () {
   check_preq || return 1
@@ -21,58 +29,29 @@ main () {
   return $((_result))
 }
 
-info () {
-  printf "\r  [ \033[00;34m..\033[0m ] %s\n" "$1"
-}
-
-user () {
-  printf "\r  [ \033[0;33m??\033[0m ] %s\n" "$1"
-}
-
-success () {
-  printf "\r\033[2K  [ \033[00;32mOK\033[0m ] %s\n" "$1"
-}
-
-fail () {
-  printf "\r\033[2K  [\033[0;31mFAIL\033[0m] %s\n" "$1"
-  echo ''
-}
-
-debug () {
-  if [ -n "$_DEBUG" ] && [ "$_DEBUG" -ne 0 ]; then
-    printf "\r  [ \033[0;33m==\033[0m ] %s\n" "$1" >&2
-  fi
-}
-
-link_dir () {
-  _lnksrc="$1"     # What the link links to
-  _lnktgt="$2"     # The link to create
-  _result=0
-  debug "$_self: START 'link_dir( $_lnksrc, $_lnktgt )'."
-  if [ -L "$_lnktgt" ]; then
-    debug "$_self: Link '$_lnktgt' already exists."
-  elif [ -e "$_lnktgt" ]; then
-    info "$_self: '$_lnktgt' already exists."
-  elif ln -s "$_lnksrc" "$_lnktgt"; then
-    success "$_self: Created link '$_lnktgt', to '$_lnksrc'."
-  else
-    fail "$_self: 'link_dir( $_lnksrc, $_lnktgt )' failed."
-    _result=1
-  fi
-  if [ ! -r "$_lnktgt" ]; then
-    info "$_self: '$_lnktgt' is not readable."
-  fi
-  debug "$_self: FINISH 'link_dir( $_lnksrc, $_lnktgt )'."
-  return $((_result))
-}
 
 check_preq () {
   info "$_self: Check for prerequisites."
   _result=0
+  # COMMANDS
   for _cmd in id docker; do
-    command -v "$_cmd" || _result=$_result+1
+    if command -v "$_cmd"; then
+      debug "$_self: check_preq() found command '$_cmd' OK."
+    else
+      fail "$_self: check_preq() did not find command '$_cmd'."
+      _result=$_result+1
+    fi
   done
-  # TODO: Check whether $HOME/Local is in $PATH.
+  # PATH ELEMENTS
+  # shellcheck disable=SC2066
+  for _path in "$HOME/Local/bin"; do
+    if [[ ":$PATH:" = *":$_path:"* ]] ; then
+      debug "$_self: check_preq() found '$_path' in \$PATH OK."
+    else
+      fail "$_self: check_preq() did not find '$_path' in \$PATH."
+      _result=$_result+1
+    fi
+  done
   return $((_result))
 }
 
@@ -122,6 +101,30 @@ pull_docker () {
   for _repo in $(docker image ls --format '{{ .Repository }}' | sort -u); do
     docker pull --quiet "$_repo" || _result=$_result+1
   done
+  return $((_result))
+}
+
+link_dir () {
+  # TODO: Can link_file() from $DOTFILES_ROOT/dotfiles.sh handle
+  # this?
+  _lnksrc="$1"     # What the link links to
+  _lnktgt="$2"     # The link to create
+  _result=0
+  debug "$_self: START 'link_dir( $_lnksrc, $_lnktgt )'."
+  if [ -L "$_lnktgt" ]; then
+    debug "$_self: Link '$_lnktgt' already exists."
+  elif [ -e "$_lnktgt" ]; then
+    info "$_self: '$_lnktgt' already exists."
+  elif ln -s "$_lnksrc" "$_lnktgt"; then
+    success "$_self: Created link '$_lnktgt', to '$_lnksrc'."
+  else
+    fail "$_self: 'link_dir( $_lnksrc, $_lnktgt )' failed."
+    _result=1
+  fi
+  if [ ! -r "$_lnktgt" ]; then
+    info "$_self: '$_lnktgt' is not readable."
+  fi
+  debug "$_self: FINISH 'link_dir( $_lnksrc, $_lnktgt )'."
   return $((_result))
 }
 
