Write new bootstrap script
New scope for .dotfiles is JUST config files.

New bootstrap ensure prerequisites and writes config file with 
DOTFILES_ROOT and DOTFILES_SHELL vars. That's all.

diff --git a/script/bootstrap b/script/bootstrap
--- a/script/bootstrap
+++ b/script/bootstrap
@@ -1,48 +1,62 @@
-#!/bin/bash
-#   bootstrap - Ensure Python, pip, local install of ansible.
+#   bootstrap:
+#     - Set $DOTFILES_SHELL, prefer /bin/bash or /bin/sh.
+#     - Run under $DOTFILES_SHELL, unless it's set to "current".
+#     - Make sure we have git.
+#     - Figure out $DOTFILES_ROOT.
+#     - Write ~/.dotfiles.conf.
 
-exit 1
-
-echo "Verify sudo access..."
-if ! sudo -v; then exit 1; fi
-echo "Detect package manager..."
-if grep -Eq 'Ubuntu|Debian' /etc/os-release && [ -x "$(which apt)" ]; then
-  # We're running Ubuntu or Debian and `apt` is executable.
-  # Make sure python3 and pip3 are available...
-  echo "Detected package manager 'apt'. Ensure Python is installed..."
-  sudo apt install python3 python3-pip -y
-  if [ -x "$(which python3)" && -x "$(which pip3)" ]; then
-    # Python and pip are available. Update tools, install Ansible...
-    echo "Found Python OK. Upgrade pip, setuptools, wheel..."
-    python3 -m pip install --user --upgrade pip setuptools wheel
-    echo "Install and test ansible..."
-    python3 -m pip install --user ansible
-    source ~/.profile
-    ansible -m ping localhost
-  else
-    # There was a problem finding or installing Python and pip.
-    echo "[fail] Unable to find or install python3 and pip3."
-  fi
-elif grep -Eq 'CentOS' /etc/os-release && [ -x "$(which yum)" ]; then
-  # We're running CentOS and yum is executable.
-  # Make sure python3 and pip3 are available...
-  echo "Detected package manager 'yum'. Ensure Python is installed..."
-  sudo yum install -y epel-release && sudo yum check-update
-  sudo yum install -y python36
-  sudo ln -fs /usr/bin/python3.6 /usr/bin/python3
-  python3 -m ensurepip --user --default-pip
-  if [ -x "$(which python3)" ] && [ -x "$(which pip)" ]; then
-    # Python and pip are available. Update tools, install Ansible...
-    echo "Found Python OK. Upgrade pip, setuptools, wheel..."
-    python3 -m pip install --user --upgrade pip setuptools wheel
-    echo "Install and test ansible..."
-    python3 -m pip install --user ansible
-    ansible -m ping localhost
-  else
-    # There was a problem finding or installing Python and pip.
-    echo "[fail] Unable to find or install python3 and pip."
-  fi
-else
-  # Did not detect package manager.
-  echo "[fail] Unable to detect package manager."
+# Make sure we can tell where we are.
+# $0 should be this script, and it should be executable.
+if [ ! -x "$0" ] || [ ! -x "${0%/*}" ]; then
+  echo -e "\n\nHow did you get here?\n\n\$0 is '$0'.\n\n"
+  exit 1
 fi
+
+# Set $DOTFILES_SHELL, prefer /bin/bash or /bin/sh.
+if [ -n "$DOTFILES_SHELL" ]; then
+  # $DOTFILES_SHELL has non-zero length, skip discovery.
+  DOTFILES_SHELL="$DOTFILES_SHELL"
+elif [ -x /bin/bash ]; then
+  # $DOTFILES_SHELL has zero length, use /bin/bash.
+  DOTFILES_SHELL=/bin/bash
+elif [ -x /bin/sh ]; then
+  # $DOTFILES_SHELL has zero length, use /bin/sh.
+  DOTFILES_SHELL=/bin/sh
+else
+  echo -e "\n\nDid not find /bin/sh or /bin/bash."\
+          "Continuing with your current shell.\n\n"
+  DOTFILES_SHELL=current
+fi
+
+# Run under $DOTFILES_SHELL, unless it's set to "current".
+if [ -z "$DOTFILES_EXEC" ] && [ "$DOTFILES_SHELL" != "current" ]; then
+  # $DOTFILES_EXEC is not set and $DOTFILES_SHELL is not "current".
+  # Set $DOTFILES_EXEC here, so we won't loop.
+  exec "$DOTFILES_SHELL" -c "DOTFILES_EXEC=$DOTFILES_SHELL $0"
+fi
+
+# Make sure we have git.
+# TODO: What other prerequisites should we check for?
+if [ ! -x $(which git) ]; then
+  echo -e "\n\nDid not find git(1). Fix that, and try again.\n\n"
+  exit 1
+fi
+
+# Figure out $DOTFILES_ROOT.
+# cd into $0's directory then ask Git to find the root of the repo.
+# TODO: More robust or elegant way to do this?
+cd "${0%/*}" && DOTFILES_ROOT="$(git rev-parse --show-toplevel)" || \
+echo -e "\n\nShit broke, yo."
+
+# Write ~/.dotfiles.conf.
+if touch ~/.dotfiles.conf; then
+  echo -e "# Generated by dotfiles/script/bootstrap." > ~/.dotfiles.conf
+  echo -e "export DOTFILES_ROOT=\"$DOTFILES_ROOT\"" >> ~/.dotfiles.conf
+  echo -e "export DOTFILES_SHELL=\"$DOTFILES_SHELL\"" >> ~/.dotfiles.conf
+else
+  echo -e "\n\nUnable to write ~/.dotfiles.conf.\n\n"
+  exit 1
+fi
+
+# If we made it this far then we think everything went OK.
+echo -e "\n\ndotfiles/script/bootstrap: Success.\n\n"
