Write setup script
This is currently locked down to only work on the "testing" topic.

diff --git a/script/setup b/script/setup
--- a/script/setup
+++ b/script/setup
@@ -1,3 +1,76 @@
-#!/bin/bash
-#  setup - Set default configs; Install and configure default apps and services.
-exit 1
+#   setup:
+#     - Load ~/.dotfiles.conf and $DOTFILES_ROOT/dotfiles.sh.
+#     - Run under $DOTFILES_SHELL, unless it's set to "current".
+#     - For each topic, run setup if it exists or just link files.
+
+# Make sure we can tell where we are.
+# $0 should be this script, and it should be executable.
+if [ ! -x "$0" ] || [ ! -x "${0%/*}" ]; then
+  echo -e "\n\nHow did you get here?\n\n\$0 is '$0'.\n\n"
+  exit 1
+fi
+
+# Load ~/.dotfiles.conf and $DOTFILES_ROOT/dotfiles.sh.
+if . ~/.dotfiles.conf && [ -x "$DOTFILES_ROOT" ]; then
+  # Found and loaded ~/.dotfiles.conf OK.
+  if . "$DOTFILES_ROOT/dotfiles.sh"; then
+    # Found and ran dotfiles.sh OK.
+    debug "$0: Loaded ~/.dotfiles.conf and $DOTFILES_ROOT/dotfiles.sh OK."
+  else
+    echo -e "\n\nMissing $DOTFILES_ROOT/dotfiles.sh"
+    echo -e "Please check your dotfiles installation.\n\n"
+    exit 1
+  fi
+else
+  echo -e "\n\nMissing ~/.dotfiles.conf"
+  echo -e "Please run dotfiles/script/bootstrap\n\n"
+  exit 1
+fi
+
+# Run under $DOTFILES_SHELL, unless it's set to "current".
+if [ -z "$DOTFILES_EXEC" ] && [ "$DOTFILES_SHELL" != "current" ]; then
+  # $DOTFILES_EXEC is not set and $DOTFILES_SHELL is not "current".
+  # Set $DOTFILES_EXEC here, so we won't loop.
+  debug "$0: 'exec \"$DOTFILES_SHELL\" -c \"DOTFILES_EXEC=$DOTFILES_SHELL $0\"'"
+  exec "$DOTFILES_SHELL" -c "DOTFILES_EXEC=$DOTFILES_SHELL $0"
+fi
+
+# For each topic, run setup if it exists or just link files.
+debug "$0: Entering topics setup..."
+cd "$DOTFILES_ROOT"
+mytopics="$(find -H . -maxdepth 3 ! -path "*/.git*" -type f \
+-name "*.symlink" -o -name "setup" | cut -d/ -f2 | sort -u)"
+
+# TODO: Un-do this. While testing, we'll just use the testing topic.
+mytopics="testing"
+
+debug "$0: Found topics '$(echo $mytopics)'."
+overwrite_all="false" backup_all="false" skip_all="false"
+for thistopic in $mytopics; do
+  info "Setting up topic '$thistopic'..."
+  if [ -r $DOTFILES_ROOT/$thistopic/setup ]; then
+    debug "$0: Running setup for '$thistopic'..."
+    if . "$DOTFILES_ROOT/$thistopic/setup"; then
+      success "Ran '$DOTFILES_ROOT/$thistopic/setup' OK."
+    else
+      fail "'$DOTFILES_ROOT/$thistopic/setup' returned an error."
+    fi
+  else
+    # $thistopic has no setup, so just link its *.symlink files.
+    debug "$0: Linking files for '$thistopic'..."
+    # TODO: Fix this so it'll handle filenames that have spaces.
+    mysymlinks="$(find -H "$DOTFILES_ROOT/$thistopic" -maxdepth 2 -name '*.symlink' ! -path '*/.git*')"
+    debug "$0: Found files to link: '$(echo $mysymlinks)'."
+    for source in $mysymlinks; do
+      target="$HOME/.$(basename "${source%.*}")"
+      debug "$0: 'link_file \"$source\" \"$target\"'"
+      if link_file "$source" "$target"; then
+        debug "$0: OK"
+      fi
+    done
+  fi
+done
+
+# If we made it this far then we think everything went OK.
+success "$0: Success."
+exit 0
