Write update script

diff --git a/script/update b/script/update
--- a/script/update
+++ b/script/update
@@ -1,3 +1,48 @@
-#!/bin/bash
-#  udpate - Update/upgrade system, apps, and services; Ensure configs.
-exit 1
+#   update:
+#     - Load ~/.dotfiles.conf and $DOTFILES_ROOT/dotfiles.sh.
+#     - Run bootstrap and setup scripts.
+
+# Make sure we can tell where we are.
+# $0 should be this script, and it should be executable.
+if [ ! -x "$0" ] || [ ! -x "${0%/*}" ]; then
+  echo -e "\n\nHow did you get here?\n\n\$0 is '$0'.\n\n"
+  exit 1
+fi
+
+# Load ~/.dotfiles.conf and $DOTFILES_ROOT/dotfiles.sh.
+if . ~/.dotfiles.conf && [ -x "$DOTFILES_ROOT" ]; then
+  # Found and loaded ~/.dotfiles.conf OK.
+  if . "$DOTFILES_ROOT/dotfiles.sh"; then
+    # Found and ran dotfiles.sh OK.
+    debug "$0: Loaded ~/.dotfiles.conf and $DOTFILES_ROOT/dotfiles.sh OK."
+  else
+    echo -e "\n\nMissing $DOTFILES_ROOT/dotfiles.sh"
+    echo -e "Please check your dotfiles installation.\n\n"
+    exit 1
+  fi
+else
+  echo -e "\n\nMissing ~/.dotfiles.conf"
+  echo -e "Please run dotfiles/script/bootstrap\n\n"
+  exit 1
+fi
+
+# Run bootstrap and setup scripts.
+
+debug "$0: '$DOTFILES_ROOT/script/bootstrap > /dev/null'"
+if "$DOTFILES_ROOT/script/bootstrap"; then
+  
+  debug "$0: '$DOTFILES_ROOT/script/setup'"
+  if "$DOTFILES_ROOT/script/setup"; then
+
+    # If we made it this far then we think everything went OK.
+    success "Update completed OK."
+    exit 0
+    
+  else
+    fail "Setup failed."
+    exit 1
+  fi
+else
+  fail "Bootstrap failed."
+  exit 1
+fi
